torgale/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings
from web.sitemap import *
#from dajaxice.core import dajaxice_autodiscover, dajaxice_config
#dajaxice_autodiscover()
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'web.views.index', name='home'),
                       url(r'^empresa/', 'web.views.empresa', name='nosotros'),
                       url(r'^servicios/', 'web.views.servicios',
                           name='servicios'),
                       url(r'^inmuebles/', 'web.views.inmuebles',
                           name='inmuebles'),
                       url(r'^detalle/(?P<codigo>\w+)/$', 'web.views.detalle',
                           name='detalle'),
                       url(r'^contacto/', 'web.views.contacto',
                           name='contacto'),
                       # url(r'^torgale/', include('torgale.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin
                       # documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs
                       # .urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^ckeditor/', include('ckeditor.urls')),
                       url(r'^media/(?P<path>.*)$',
                           'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT, }),
                       #url(dajaxice_config.dajaxice_url,
                       # include('dajaxice.urls')),
                       #url(r'^%s' % settings.DAJAXICE_MEDIA_PREFIX,
                       # include('dajaxice.urls'))
                       )

sitemaps = {
    'static': StaticSitemap,
    'inmuebles': OfertaSitemap,
}

urlpatterns += patterns('',
                       url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views'
                                            '.sitemap', {'sitemaps': sitemaps}),
                       url(r'^humans\.txt$', TemplateView.as_view(
                         template_name='humans.txt')),
                       url(r'^robots\.txt$', TemplateView.as_view(
                         template_name='robots.txt')),
                       url(r'^channel\.html$', TemplateView.as_view(
                           template_name='channel.html')),
)

web/forms.py
# encoding: utf-8
__author__ = 'Gollum23'

from django import forms


class ContactForm(forms.Form):
    fullname = forms.RegexField(
        label='Nombre Completo',
        max_length=100,
        regex=r'^[a-zA-Z ]+$',
        error_message='Solo se permiten letras'
    )
    phone = forms.IntegerField(
        error_messages={
            'invalid': 'Ingrese un numero telefonico valido'}
    )
    subject = forms.CharField(max_length=200)
    email = forms.EmailField(
        error_messages={
            'invalid': 'Ingrese una dirección valida'}
    )
    message = forms.CharField(
        widget=forms.Textarea, max_length=1000)

templates/base.html
{% load static %}{% get_static_prefix as STATIC_PREFIX %}
{% load url from future %}
<!doctype html>
<html lang="es-mx">
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb#
                  website: http://ogp.me/ns/website#">
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{#    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />#}
    <meta property="og:type" content="website">
    {% block ogurl %}<meta property="og:url"
                           content="http://torgale.com.co{% url 'home' %}">
    {%  endblock %}
    <meta property="og:image" content="http://torgale.com.co/media/logo.png">
    {% block ogtitle %}
        <meta property="og:title" content="Inmobiliaria Torgale">
    {% endblock %}
    <meta property="og:description"
          content="Inmobiliaria Torgale,
    venta y arrendamiento de inmuebles en bogotá">
    <meta name="author" content="Inmobiliaria Torgale">
    <meta name="description" content="Inmobiliaria Torgale,
    venta y arrendamiento de inmuebles en bogotá">

    <link href="{{ STATIC_PREFIX }}images/favicon.ico" type="image/x-icon" rel="shortcut icon">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_PREFIX }}css/normalize.css"
          media="all">
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/layout.css">
    <link rel="stylesheet" href="{{ STATIC_PREFIX }}css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_PREFIX }}css/jquery.fancybox.css" media="screen">
    {% block extraStyles %}{% endblock %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    {% block extraJStop %}{% endblock %}
</head>
<body>
    <div id="superior">
        <header>
            <div id="ribbon"></div>
            <div id="logo">
                <a href="{% url 'home' %}"><h1>Inmobiliaria
                    Torgale</h1></a>
            </div>
            {% comment %}<nav>
                <ul>
                    <li><a href="{% url web.views.index %}">Inicio</a></li>
                    <li><a href="{% url web.views.empresa %}">Empresa</a></li>
                    <li><a href="/servicios/">Servicios</a></li>
                    <li><a href="{% url web.views.inmuebles %}">Oferta Inmobiliaria</a></li>
                    <li><a href="{% url web.views.contacto %}">Contacto</a></li>
                </ul>
            </nav>{% endcomment %}
            <div class="navbar">
                <div>
                    <div class="container">
                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <nav class="nav-collapse collapse">
                            <ul>
                                <li><a href="{% url 'home' %}">Inicio</a></li>
                                <li><a href="{% url 'nosotros' %}">Empresa</a></li>
                                <li><a href="{% url 'servicios' %}">Servicios</a></li>
                                <li><a href="{% url 'inmuebles' %}">Oferta Inmobiliaria</a></li>
                                <li><a href="{% url 'contacto' %}">Contacto</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>
        </header>
    </div>
    <div class="clearfix"></div>
    {% block imgvalor %}<div id="imgvalor" class="{{ imgvalor }}"></div>{% endblock %}
    {% block body %}{% endblock %}
    <div id="inferior">
        <footer>
            <div id="menuaux">
                <ul>
                    <li><a href="{% url 'home' %}">Inicio</a></li>
                    <li><a href="{% url 'nosotros' %}">Empresa</a></li>
                    <li><a href="{% url 'servicios' %}">Servicios</a></li>
                    <li><a href="{% url 'inmuebles' %}">Oferta
                        Inmobiliaria</a></li>
                    <li><a href="{% url 'contacto' %}">Contacto</a></li>
                </ul>
            </div>
            <div id="social">
                <p>Siguenos en las redes sociales</p>
                <ul>
                    <li><a href="#" class="facebook"></a></li>
                    <li><a href="#" class="plus"></a></li>
                    <li><a href="#" class="skype"></a></li>
                    <li><a href="#" class="twitter"></a></li>
                </ul>
            </div>
            <div id="copyright">
                <p>Inmobiliaria Torgale - 2012</p>
                <p>Diseñado por mantistecnologia.co</p>
            </div>

        </footer>
    </div>

    <script type="text/javascript" src="{{ STATIC_PREFIX }}js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_PREFIX }}js/jquery.fancybox.pack.js?v=2.1.4"></script>
    {% block extraJS %}{% endblock %}
    <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-38523716-1']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load url from future %}
{% block title %}Inmobiliaria Torgale - Contacto{% endblock %}
{% block ogurl %}
    <meta property="og:url" content="http://torgale.com.co{% url 'contacto' %}">
{% endblock %}
{% block ogtitle %}
    <meta property="og:title" content="Inmobiliaria Torgale - Contacto">
{% endblock %}
{% block body %}
    <section id="principal">
        <div id="contactform">
            <h2>Contactenos</h2>
            {% if messaget != None %}
                <p>{{ messaget }}</p>
            {% endif %}
            <form id="formcontact" action="{% url 'contacto' %}" method="post"
                    >{% csrf_token %}
                {#    {{ contacform.as_p }}#}
                {{ contacform.non_field_errors }}
                <div class="fieldwrapper">
                    {{ contacform.fullname.errors }}
                    <label for="id_fullname">Nombres Completos</label>
                    {{ contacform.fullname }}
                </div>
                <div class="fieldwrapper">
                    {{ contacform.phone.errors }}
                    <label for="id_phone">Teléfono</label>
                    {{ contacform.phone }}
                </div>
                <div class="fieldwrapper">
                    {{ contacform.subject.errors }}
                    <label for="id_subject">Asunto</label>
                    {{ contacform.subject }}
                </div>
                <div class="fieldwrapper">
                    {{ contacform.email.errors }}
                    <label for="id_email">Correo Electronico</label>
                    {{ contacform.email }}
                </div>
                <div class="fieldwrapper">
                    {{ contacform.message.errors }}
                    <label for="id_message">Mensaje</label>
                    {{ contacform.message }}
                </div>
                <input type="submit" value="Enviar!" />
                <div class="clear"></div>
            </form>
        </div>
        <div id="imgcontacto">
            <img src="/media/contactenos.jpg" alt="Contactenos">
        </div>
    </section>

{% endblock %}
{% block extraJS %}

{% endblock %}

templates/detalle.html
{% extends 'base.html' %}
{% load url from future %}
{% load humanize %}
{% block title %}Inmobiliaria Torgale - {{ inmueble.codInmueble }}{% endblock %}
{% block ogurl %}
    <meta property="og:url"
          content="http://torgale.com.co{% url 'detalle' inmueble.codInmueble %}">
{% endblock %}
{% block ogtitle %}
    <meta property="og:title" content="Inmobiliaria Torgale - {{ inmueble.codInmueble }}">
{% endblock %}
{% block extraStyles %}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_PREFIX }}css/flexslider.css" media="all">
{#    <link rel="stylesheet" type="text/css" href="{{ STATIC_PREFIX }}css/jquery.lightbox-0.5.css">#}
{% endblock %}
{% block body %}
    <section id="principal">
    {#Columna izquierda#}
        <div id="detallelc">
            <section class="slider">
                <div id="slider" class="flexslider">
                    <ul class="slides">
                        {% for img in inmueble.images.all %}
                            <li>
                                <img src="/media/{{ img.imagen }}">
                            </li>
                        {% empty %}
                            <li>
                                <img src="/media/sin_image.png">
                            </li>
                        {% endfor %}
{#                        {% if images.count > 0 %}#}
{#                            {% for slide in images %}#}
{#                                <li>#}
{#                                    <img src="/media/{{ slide.imagen }}">#}
{#                                </li>#}
{#                            {% endfor %}#}
{#                        {% else %}#}
{#                            <li>#}
{#                                <img src="/media/sin_image.png">#}
{#                            </li>#}
{#                        {% endif %}#}
                    </ul>
                </div>
                {% if inmueble.images.all.count > 1 %}
                    <div id="carousel" class="flexslider">
                        <ul class="slides">
                            {% for img in inmueble.images.all %}
                                <li>
                                    <img src="/media/{{ img.imagen }}">
                                </li>
                            {% endfor %}
{#                            {% for slide in images %}#}
{#                                <li>#}
{#                                    <img src="/media/{{ slide.imagen }}">#}
{#                                </li>#}
{#                            {% endfor %}#}
                        </ul>
                    </div>
                {% endif %}
            </section>
            <section id="ubicacion">
                <a href="http://maps.google.com/maps/api/staticmap?center={{ inmueble.lat }},{{ inmueble.lon }}&zoom=13&size=420x320&maptype=roadmap&markers=color:blue|{{ inmueble.lat }},{{ inmueble.lon }}&sensor=false">Ver Ubicación</a>

                <div id="mapa">
                    <h3>Ubicación</h3>
                    <img src="http://maps.google.com/maps/api/staticmap?center={{ inmueble.lat }},{{ inmueble.lon }}&zoom=15&size=240x180&maptype=roadmap&markers=color:blue|{{ inmueble.lat }},{{ inmueble.lon }}&sensor=false"
                         alt="Ubicación">
                </div>


            </section>
        </div>
    {#Columna Derecha#}
        <div id="detallerc">
            <section id="info">
                <div id="volver"><a href="javascript:window.history.back()">Volver al listado</a></div>
                <h2>Descripción del Inmueble</h2>
                <p class="detalle"><span>Código: </span> {{ inmueble.codInmueble }}</p>
                <p class="detalle"><span>Tipo de Inmueble: </span> {{ inmueble.claseInmueble }}</p>
                <p class="detalle"><span>Zona: </span> {{ inmueble.zona }}</p>
                <p class="detalle"><span>Barrio: </span> {{ inmueble.barrio }}</p>
                <p class="detalle"><span>Dirección: </span> {{ inmueble.direccion }}</p>
                <p class="detalle"><span>Estrato: </span> {{ inmueble.estrato }}</p>
                <p class="detalle"><span>No. habitaciones: </span> {{ inmueble.habitaciones }}</p>
                <p class="detalle"><span>No. closets: </span> {{ inmueble.closets }}</p>
                <p class="detalle"><span>No. baños: </span> {{ inmueble.banos }}</p>
                <p class="detalle"><span>Cocina integral: </span> {{ inmueble.cocina }}</p>
                <p class="detalle"><span>Gas natural: </span> {{ inmueble.serviciogas }} </p>
                <p class="detalle"><span>Piso alcobas: </span> {{ inmueble.pisoalcobas }} </p>
                <p class="detalle"><span>Piso comedor: </span> {{ inmueble.pisocomedor }} </p>
                <p class="detalle"><span>Piso sala: </span> {{ inmueble.pisosala }} </p>
                {% if inmueble.cantPisos != '' %}
                    <p class="detalle"><span>No de pisos: </span> {{ inmueble.cantPisos }}</p>
                {% endif %}
                {% if inmueble.numeroPiso != '' %}
                    <p class="detalle"><span>Piso No.: </span> {{ inmueble.numeroPiso }}</p>
                {% endif %}
                <p class="detalle"><span>Garaje: </span> {{ inmueble.garaje }}</p>
                <p class="detalle"><span>Ascensor: </span> {{ inmueble.ascensor }} </p>
                <p class="detalle"><span>Área construida: </span> {{ inmueble.areac }} m<sup>2</sup></p>
                <p class="detalle"><span>Área total: </span> {{ inmueble.areat }} m<sup>2</sup></p>
                <p class="detalle"><span>Tiempo de construcción: </span> {{ inmueble.contruccion }}</p>
                <p class="detalle"><span>Propiedad horizontal: </span> {{ inmueble.horizontal }} </p>
                <p class="detalle"><span>Conjunto cerrado: </span> {{ inmueble.conjunto }} </p>
                {% if inmueble.venta != Null %}
                    <p class="detalle"><span>Precio venta: </span> {{ inmueble.venta|intcomma }} </p>
                {% endif %}
                {% if inmueble.arriendo != Null %}
                    <p class="detalle"><span>Canon arriendo: </span> {{ inmueble.arriendo|intcomma }}</p>
                {% endif %}
                {% if inmueble.administracion != Null %}
                    <p class="detalle"><span>Valor administración: </span> {{ inmueble.administracion|intcomma }} </p>
                {% endif %}
                {% if inmueble.adminIncluida != 'n/a' %}
                    <p class="detalle"><span>Administración incluida: </span> {{ inmueble.adminIncluida }} </p>
                {% endif %}
                {% autoescape off %}
                    <p class="detalle"><span>Observaciones: </span> {{ inmueble.observaciones }}</p>
                {% endautoescape %}
            </section>
        </div>


        <div class="clearfix"></div>
    </section>
{% endblock %}
{% block extraJS %}
    <script type="text/javascript" src="{{ STATIC_PREFIX }}js/jquery.flexslider-min.js"></script>
{#    <script type="text/javascript" src="{{ STATIC_PREFIX }}js/jquery.lightbox-0.5.min.js"></script>#}
    <script type="text/javascript">
        $(document).on("ready",function(){
            $('#carousel').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: false,
                slideshow: false,
                itemWidth: 100,
                itemMargin: 5,
                asNavFor: '#slider'
            });
            $('#slider').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: false,
                slideshow: false,
                sync: '#carousel',
                start:function(slider){
                    $('body').removeClass('loading');
                }
            });
{#            $('section#ubicacion a').lightBox({#}
{#                imageLoading:'{{ STATIC_PREFIX }}images/lightbox-ico-loading.gif',#}
{#                imageBtnClose:'{{ STATIC_PREFIX }}images/lightbox-btn-close.gif'#}
{#            });#}
        });
    </script>
{% endblock %}

templates/empresa.html
{% extends "base.html" %}
{% load url from future %}
{% block title %}Inmobiliaria Torgale - Nosotros{% endblock %}
{% block ogurl %}
    <meta property="og:url"
          content="http://torgale.com.co{% url 'nosotros' %}">
{% endblock %}
{% block ogtitle %}
    <meta property="og:title" content="Inmobiliaria Torgale - Nosotros">
{% endblock %}
{% block body %}
    <section id="principal">
        <article id="nosotros">
            <div id="leftc">
                <h3>Sobre nosotros:</h3>
                <p>Somos una empresa con más de 30 años de trayectoria,
                    con un personal competente y amplio para los diferentes
                    desafíos que se nos presenten, trabajando con dedicación
                    persistencia, profesionalismo, disciplina y honestidad.
                    Nuestra razón de ser son nuestros usuarios,
                    quienes durante toda éste  recorrido han depositado su
                    confianza en nosotros, hecho que nos compromete en
                    trabajar aún más y mejor, día y día,
                    para seguir posicionándonos  en el mercado inmobiliario y
                    brindarles a ustedes;  nuestros clientes,
                    más que un servicio, la tranquilidad que no solo
                    necesitan, sino se merecen en la administración y cuidado
                    no solo en  sus inmuebles sino  en todo un patrimonio.</p>
                <img src="/media/img_nosotros.jpg" alt="Sobre Nosotros"
                         title="Sobre Nosotros">
            </div>
            <div id="rigthc">
                <img src="/media/mapa_oficina.jpg" alt="Nuestra oficina: Cr 8
                 No 15-80" title="Nuestra oficina">
            </div>
        </article>
        <div id="actions">
            <a href="{% url 'inmuebles' %}">
                <div id="callsto1" class="callsto">
                    <p>Conozca nuestra oferta inmobiliaria</p>
                    <p class="cuadro">Ver Inmuebles</p>
                </div>
            </a>
            <a id="requirements" href="#rcontent">
                <div id="callsto2" class="callsto">
                    <p>Conozca los requisitos</p>
                    <p class="cuadro">Ver Requisitos</p>
                </div>
            </a>
            <a href="/media/formulario.pdf" target="_blank">
                <div id="callsto3" class="callsto">
                    <p>Descargar formulario de solicitud</p>
                    <p class="cuadro">Descargar</p>
                </div>
            </a>
            <div class="clearfix"></div>
        </div>
        <div id="rcontent">
            <h2>Requerimientos</h2>
            <ol>
                <li>Formulario de arrendamiento completamente deligenciado</li>
                <li>
                    Documentos del Arrendatario
                    <ul>
                        <li>
                            Si es Empleado
                            <ul>
                                <li>Certificado laboral no mayor a 30 días, que
                                    incluya salario, cargo, tiempo de servicio.
                                </li>
                                <li>Tres últimos comprobantes de pago</li>
                                <li>Certificado de libertad no mayor a treinta (30) días (Opcional)</li>
                            </ul>
                        </li>
                        <li>
                            Si es Independiente
                            <ul>
                                <li>Fotocopia del documento de identidad</li>
                                <li>Cámara de comercio vigente</li>
                                <li>Declaración de renta del último año o carda de no declarante</li>
                                <li>Extractos bancarios de los últimos tres (3) meses</li>
                                <li>Certificado de libertad no mayor a treinta (30) días (Opcional)</li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    Dos codeudores uno con finca raíz y el otro que sea solvente y demuestre ingresos.
                    <ul>
                        <li>
                            Codeudor con finca raíz
                            <ul>
                                <li>Adjuntar certificado de libertad de Bogotá D.C., no mayor a treinta(30) días que no tenga afectación a vivienda familiar, patrimonio de familia ni embargos.</li>
                            </ul>
                        </li>
                        <li>
                            Codeudor solvente
                            <ul>
                                <li>
                                    Si es empleado
                                    <ul>
                                        <li>Certificado laboral no mayor a treinta (30) días. que incluya salario, cargo, tiempo de servicio.</li>
                                        <li>Tres últimos comprobantes de pago</li>
                                        <li>Certificado de libertad no mayor a treinta (30) días (Opcional)</li>
                                    </ul>
                                </li>
                                <li>
                                    Si es independiente
                                    <ul>
                                        <li>Fotocopia del documento de identidad</li>
                                        <li>Cámara de comercio vigente</li>
                                        <li>Declaración de renta del último año o carta de no declarante</li>
                                        <li>Extractos bancarios de los últimos tres (3) meses</li>
                                        <li>Certificado de libertad no mayor a treinta (30) días (Opcional)</li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>Fotocopias de las cédulas, tanto del arrendatario como de los dos codeudores</li>
            </ol>
            <p>* El valor del estudio es de $60.000, dinero que se reembolsará si no es aprobado el mismo.</p>
        </div>
    </section>
{% endblock %}
{% block extraJS %}
    <script type="text/javascript">
        $(document).on("ready", function(){
            $('#requirements').fancybox();
        })
    </script>
{% endblock %}

templates/inmuebles.html
{% extends 'base.html' %}
{% load url from future %}
{% block title %}Inmobiliaria Torgale - Oferta Inmobiliaria{% endblock %}
{% block ogurl %}
    <meta property="og:url"
          content="http://torgale.com.co{% url 'inmuebles' %}">
{% endblock %}
{% block ogtitle %}
    <meta property="og:title"
          content="Inmobiliaria Torgale - Oferta
    Inmobiliaria">
{% endblock %}
{% block body %}
    <section id="principal">
        <div id="filters">
            {{ filtros }}
        </div>
        <h2>Inmuebles</h2>
        <section id="inmuebles">
            {% for inmueble in inmuebles %}
                <article id="{{ inmueble.codInmueble }}" class="inmueble mright20">
                    <a href="{% url 'detalle' inmueble.codInmueble%}">
                        <div class="imgportada">
                            {% for img in inmueble.images.all %}
                                {% if img.portada == 'si' %}
                                    <img src="/media/{{ img.imagen }}" alt="{{ img.descripcion|striptags }}">
                                {% endif %}
                            {% empty %}
                                <img src="/media/sin_image.png" alt="Sin Imagen">
                            {% endfor %}
                        </div>
                        <div class="infoinmueble">
                            <p>{{ inmueble.claseInmueble }} en
                                {{ inmueble.negocio }}</p>
                            <p><span>Zona: </span>{{ inmueble.zona }}</p>
                            <p><span>Barrio: </span>{{ inmueble.barrio }}</p>
                            <p class="enlinea">{{ inmueble.areac }} m<sup>2</sup> |
                                {{ inmueble.habitaciones }} habitacion{{ inmueble.habitaciones|pluralize:'es' }} | </p>
                            <p class="enlinea">{{ inmueble.banos }} baño{{ inmueble.banos|pluralize }}</p>
                        </div>
                        <div class="overlay">
                            <span class="msg">Ver Detalle del inmueble</span>
                        </div>
                    </a>
                </article>

            {% endfor %}
            <div class="clearfix"></div>
        </section>
    </section>
{% endblock %}

{% block extraJS %}
{#    <script type="text/javascript">#}
{#        $('select').on('change',function(){#}
{#            $('#consulta').submit()#}
{#        })#}
{#    </script>#}
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block body %}
{{ messaget }}
{% endblock %}